# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
