# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 22:09
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentduration',
            name='exp_duration',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=4, unique=True, verbose_name='Experiment Duration'),
        ),
        migrations.AlterField(
            model_name='experimentrep',
            name='no_replication',
            field=models.SmallIntegerField(default=0, verbose_name='Experiment Replication Number'),
        ),
        migrations.AlterField(
            model_name='nitrogenapplied',
            name='nitrogen_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6, unique=True),
        ),
        migrations.AlterField(
            model_name='researchexperimentunit',
            name='incubation_days',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=4, null=True, verbose_name='Incubation Days'),
        ),
        migrations.AlterField(
            model_name='researchexperimentunit',
            name='lower_soil_depth',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='researchexperimentunit',
            name='upper_soil_depth',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=5, null=True),
        ),
    ]
