# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='research_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
