# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20170224_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdetails',
            name='slug',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
