# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20170224_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdetails',
            name='exp_detail',
            field=models.TextField(unique=True, verbose_name='Experiment Details'),
        ),
    ]
