# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20170212_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementseason',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='measurementseason',
            name='user',
        ),
        migrations.RemoveField(
            model_name='measurementyear',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='measurementyear',
            name='measurementseason',
        ),
        migrations.RemoveField(
            model_name='measurementyear',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='measurementyear',
            name='user',
        ),
        migrations.DeleteModel(
            name='MeasurementSeason',
        ),
        migrations.DeleteModel(
            name='MeasurementYear',
        ),
    ]
