# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20170224_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdetails',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
