# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20170212_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='research',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
