# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20170224_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlresearch',
            name='outcome_uom',
            field=models.CharField(blank=True, default='kg/ha', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentresearch',
            name='outcome_uom',
            field=models.CharField(blank=True, default='kg/ha', max_length=200, null=True),
        ),
    ]
