# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20170212_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchspecies',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='researchspecies',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='researchspecies',
            name='research',
        ),
        migrations.RemoveField(
            model_name='researchspecies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='species',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='species',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResearchSpecies',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
