# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 21:54
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20170226_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlresearch',
            name='mean_outcome',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, null=True, verbose_name='Mean outcome'),
        ),
        migrations.AlterField(
            model_name='controlresearch',
            name='std_outcome',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, null=True, verbose_name='Standard outcome'),
        ),
        migrations.AlterField(
            model_name='treatmentresearch',
            name='mean_outcome',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, null=True, verbose_name='Mean outcome'),
        ),
        migrations.AlterField(
            model_name='treatmentresearch',
            name='std_outcome',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, null=True, verbose_name='Standard outcome'),
        ),
    ]
