# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20170226_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlresearch',
            name='outcome_uom',
            field=models.CharField(default='kg/ha', max_length=200),
        ),
        migrations.AlterField(
            model_name='treatmentresearch',
            name='outcome_uom',
            field=models.CharField(default='kg/ha', max_length=200),
        ),
    ]
