# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_auto_20170226_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentresearch',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='treatmentresearch',
            name='experimentdetails',
        ),
        migrations.RemoveField(
            model_name='treatmentresearch',
            name='experimentduration',
        ),
        migrations.RemoveField(
            model_name='treatmentresearch',
            name='experimentrep',
        ),
        migrations.RemoveField(
            model_name='treatmentresearch',
            name='measurementyear',
        ),
        migrations.RemoveField(
            model_name='treatmentresearch',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='treatmentresearch',
            name='nitrogenapplied',
        ),
        migrations.RemoveField(
            model_name='treatmentresearch',
            name='user',
        ),
        migrations.DeleteModel(
            name='TreatmentResearch',
        ),
    ]
