# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_auto_20170314_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdetails',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='experimentdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='research',
            name='experimentdetails',
        ),
        migrations.AddField(
            model_name='research',
            name='exp_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Experiment Details'),
        ),
        migrations.DeleteModel(
            name='ExperimentDetails',
        ),
    ]
