# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_auto_20170329_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='nitrogenapplied',
            name='nitrogen_source',
            field=models.CharField(blank=True, choices=[('Organic', 'Organic'), ('Inorganic', 'Inorganic')], max_length=30, null=True),
        ),
    ]
