# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_auto_20170417_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
    ]
