# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0020_auto_20170418_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='user',
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
