# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0022_auto_20170418_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
