# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0023_auto_20170418_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentduration',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='experimentduration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='research',
            name='experimentduration',
        ),
        migrations.DeleteModel(
            name='ExperimentDuration',
        ),
    ]
