# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0024_auto_20170419_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchexperimentunit',
            name='incubation_days',
        ),
        migrations.RemoveField(
            model_name='researchexperimentunit',
            name='lower_soil_depth',
        ),
        migrations.RemoveField(
            model_name='researchexperimentunit',
            name='upper_soil_depth',
        ),
    ]
