# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0025_auto_20170419_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='mean_outcome',
        ),
        migrations.RemoveField(
            model_name='research',
            name='outcome_uom',
        ),
        migrations.RemoveField(
            model_name='research',
            name='std_outcome',
        ),
    ]
