# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0026_auto_20170419_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentrep',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='experimentrep',
            name='user',
        ),
        migrations.RemoveField(
            model_name='research',
            name='experimentrep',
        ),
        migrations.DeleteModel(
            name='ExperimentRep',
        ),
    ]
