# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0033_diversity_researchdiversity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementseason',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='measurementseason',
            name='user',
        ),
        migrations.RemoveField(
            model_name='measurementyear',
            name='measurementseason',
        ),
        migrations.DeleteModel(
            name='MeasurementSeason',
        ),
    ]
