# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0040_auto_20170421_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nitrogenapplied',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='nitrogenapplied',
            name='user',
        ),
        migrations.RemoveField(
            model_name='research',
            name='nitrogenapplied',
        ),
        migrations.DeleteModel(
            name='NitrogenApplied',
        ),
    ]
