# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0041_auto_20170421_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='NitrogenApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('nitrogen_amount', models.DecimalField(decimal_places=2, max_digits=6, unique=True)),
                ('amount_uom', models.CharField(default='kg/ha', max_length=12, verbose_name='Nitrogen UOM')),
                ('nitrogen_source', models.CharField(choices=[('Organic', 'Organic'), ('Inorganic', 'Inorganic')], max_length=30)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='research_nitrogenapplied', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Nitrogen Applied',
            },
        ),
        migrations.CreateModel(
            name='ResearchNitrogenApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='research_researchnitrogenapplied', to=settings.AUTH_USER_MODEL)),
                ('nitrogenapplied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.NitrogenApplied')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Research Nitrogen Applied',
            },
        ),
    ]
