# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0042_nitrogenapplied_researchnitrogenapplied'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nitrogenapplied',
            unique_together=set([('nitrogen_amount', 'nitrogen_source')]),
        ),
    ]
