# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0043_auto_20170421_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nitrogenapplied',
            name='amount_uom',
            field=models.CharField(choices=[('kg/ha', 'kg/ha'), ('kg manure/ha', 'kg manure/ha')], max_length=12),
        ),
    ]
