# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0047_auto_20170502_1209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurementyear',
            unique_together=set([('measurement_year', 'second_year')]),
        ),
    ]
