from .outcomeindicator.outcomeindicatorviews import outcome_indicator_views
from .researchoutcomeindicator.researchoutcomeindicatorviews import research_outcome_indicator_views
from .soilmeasurement.soilmeasurementviews import soil_measurement_views
from .experimentoutcome.experimentoutcomeviews import experiment_outcome_views
from .indicatortype.indicatortypeviews import indicator_type_views
from .indicator.indicatorviews import indicator_views
from .subpillar.subpillarviews import subpillar_views

outcome_indicator_views = outcome_indicator_views()
research_outcome_indicator_views = research_outcome_indicator_views()
soil_measurement_views = soil_measurement_views()
experiment_outcome_views = experiment_outcome_views()
indicator_type_views = indicator_type_views()
indicator_views = indicator_views()
subpillar_views = subpillar_views()
