from .controlresearch.controlresearchserializers import control_research_serializers
from .treatmentresearch.treatmentresearchserializers import treatment_research_serializers
from .experimentrep.experimentrepserializers import experiment_rep_serializers
from .nitrogenapplied.nitrogenappliedserializers import nitrogen_applied_serializers
from .experimentdetails.experimentdetailsserializers import experiment_details_serializers
from .experimentduration.experimentdurationserializers import experiment_duration_serializers


treatment_research_serializers = treatment_research_serializers()
control_research_serializers = control_research_serializers()
experiment_rep_serializers = experiment_rep_serializers()
nitrogen_applied_serializers = nitrogen_applied_serializers()
experiment_details_serializers = experiment_details_serializers()
experiment_duration_serializers = experiment_duration_serializers()
