# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20160907_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature_uom',
            field=models.CharField(default='\xb0C', max_length=5, verbose_name='Temperature UOM'),
        ),
    ]
