# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_precipitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precipitation',
            options={'ordering': ['-time_created', '-last_update'], 'verbose_name_plural': 'Precipitation'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['-time_created', '-last_update'], 'verbose_name_plural': 'Temperature'},
        ),
    ]
