# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20160930_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precipitation',
            name='precipitation',
            field=models.DecimalField(decimal_places=2, max_digits=7, unique=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, unique=True),
        ),
    ]
