# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 22:09
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20161004_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='precipitation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=7, unique=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5, unique=True),
        ),
    ]
