# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20170224_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precipitation',
            name='precipitation_desc',
            field=models.CharField(blank=True, choices=[('Mean Annual', 'Mean Annual'), ('Mean Seasonal', 'Mean Seasonal'), ('Total Annual', 'Total Annual'), ('Total Seasonal', 'Total Seasonal')], max_length=65, null=True),
        ),
    ]
