# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20170329_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='site_type',
            field=models.CharField(blank=True, choices=[('On-Farm', 'On-Farm'), ('On-Station', 'On-Station'), ('Survey', 'Survey'), ('Greenhouse', 'Greenhouse')], max_length=30, null=True),
        ),
    ]
