# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_location_site_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([]),
        ),
    ]
