from .research.researchviews import research_views
from .nitrogenapplied.nitrogenappliedviews import nitrogen_applied_views
from .researchmeasurementyear.researchmeasurementyearviews import research_measurement_year_views
from .measurementyear.measurementyearviews import measurement_year_views
from .researchdiversity.researchdiversityviews import research_diversity_views
from .diversity.diversityviews import diversity_views
from .researchexperimentdescription.researchexperimentdescriptionviews import research_experiment_description_views
from .experimentdescription.experimentdescriptionviews import experiment_description_views
from .researchexperimentreplicate.researchexperimentreplicateviews import research_experiment_replicate_views
from .experimentreplicate.experimentreplicateviews import experiment_replicate_views
from .researchauthor.researchauthorviews import research_author_views
from .journal.journalviews import journal_views
from .author.authorviews import author_views
from .experimentunit.experimentunitviews import experiment_unit_views
from .researchexperimentunit.researchexperimentunitviews import research_experiment_unit_views
from .breed.breedviews import breed_views
from .experimentunitcategory.experimentunitcategoryviews import experiment_unit_category_views


research_views = research_views()
nitrogen_applied_views = nitrogen_applied_views()
research_measurement_year_views = research_measurement_year_views()
measurement_year_views = measurement_year_views()
research_diversity_views = research_diversity_views()
diversity_views = diversity_views()
research_experiment_description_views = research_experiment_description_views()
experiment_description_views = experiment_description_views()
research_experiment_replicate_views = research_experiment_replicate_views()
experiment_replicate_views = experiment_replicate_views()
research_author_views = research_author_views()
journal_views = journal_views()
author_views = author_views()
experiment_unit_views = experiment_unit_views()
research_experiment_unit_views = research_experiment_unit_views()
breed_views = breed_views()
experiment_unit_category_views = experiment_unit_category_views()
