# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('som', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Soil Organic Matter')),
                ('som_uom', models.CharField(blank=True, max_length=6, null=True, verbose_name='Soil Organic Matter UOM')),
                ('initial_soc', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Initial Soil Organic Carbon')),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('soil_years', models.SmallIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soils_soil', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Soils',
            },
        ),
    ]
