# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('soil_type', models.TextField()),
                ('classification', models.TextField()),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soils_soiltype', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Soil Types',
            },
        ),
        migrations.AddField(
            model_name='soil',
            name='soil_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='soils.SoilType'),
            preserve_default=False,
        ),
    ]
