# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soils', '0004_auto_20160921_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='soil_type',
        ),
    ]
