# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soils', '0006_soil_soiltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='soil_texture',
        ),
    ]
