# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soils', '0007_remove_soil_soil_texture'),
    ]

    operations = [
        migrations.AddField(
            model_name='soil',
            name='soiltexture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='soils.SoilTexture'),
            preserve_default=False,
        ),
    ]
