# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soils', '0008_soil_soiltexture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltexture',
            name='soil_texture',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='soiltype',
            name='soil_type',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
