# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soils', '0009_auto_20160921_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='som',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Soil Organic Matter-SOM'),
        ),
    ]
