# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soils', '0010_auto_20160929_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soil',
            name='soiltexture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soils.SoilTexture', verbose_name='Soil Texture'),
        ),
        migrations.AlterField(
            model_name='soil',
            name='soiltype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soils.SoilType', verbose_name='Soil Type'),
        ),
    ]
