# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsaPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('practice_code', models.CharField(help_text='User defined CSA practice code', max_length=6, unique=True)),
                ('sub_practice_level', models.TextField(blank=True, null=True)),
                ('sub_subpractice_level', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'CSA Practices',
            },
        ),
        migrations.CreateModel(
            name='CsaTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('csa_theme', models.CharField(max_length=80, unique=True, verbose_name='CSA theme')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='csa_practice_csatheme', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'CSA Practice Themes',
            },
        ),
        migrations.CreateModel(
            name='PracticeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('practice_level', models.CharField(max_length=150, unique=True)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='csa_practice_practicelevel', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'CSA Practice Levels',
            },
        ),
        migrations.CreateModel(
            name='PracticeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('practice_type', models.CharField(max_length=120, unique=True, verbose_name='Practice category')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='csa_practice_practicetype', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'CSA Practice Types',
            },
        ),
        migrations.CreateModel(
            name='ResearchCsaPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('csapractice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csa_practice.CsaPractice', verbose_name='CSA practice')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='csa_practice_researchcsapractice', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Research CSA Practices',
            },
        ),
        migrations.AddField(
            model_name='csapractice',
            name='csatheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csa_practice.CsaTheme', verbose_name='CSA theme'),
        ),
        migrations.AddField(
            model_name='csapractice',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='csa_practice_csapractice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csapractice',
            name='practicelevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csa_practice.PracticeLevel', verbose_name='Practice level'),
        ),
        migrations.AddField(
            model_name='csapractice',
            name='practicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csa_practice.PracticeType', verbose_name='Practice category'),
        ),
        migrations.AddField(
            model_name='csapractice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
