# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csa_practice', '0002_auto_20170131_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csapractice',
            name='csatheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csa_practice.CsaTheme', verbose_name='CSA theme'),
        ),
        migrations.AlterField(
            model_name='csapractice',
            name='practicelevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csa_practice.PracticeLevel', verbose_name='Practice level'),
        ),
        migrations.AlterField(
            model_name='csapractice',
            name='practicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='csa_practice.PracticeType', verbose_name='Practice category'),
        ),
        migrations.AlterField(
            model_name='csatheme',
            name='csa_theme',
            field=models.CharField(max_length=80, unique=True, verbose_name='CSA theme'),
        ),
    ]
