# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_practice', '0005_auto_20170201_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csatheme',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
