# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csa_practice', '0007_researchcsapractice'),
    ]

    operations = [
        migrations.AddField(
            model_name='csapractice',
            name='sub_subpractice_level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
