# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('mean_outcome', models.DecimalField(decimal_places=2, max_digits=8)),
                ('std_outcome', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('outcome_uom', models.CharField(default='kg/ha', max_length=100)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_experimentoutcome', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Experiment Outcomes',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('indicator', models.CharField(max_length=120, unique=True)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_indicator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('indicator_type', models.CharField(max_length=120, unique=True, verbose_name='Indicator category')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_indicatortype', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Indicator Types',
            },
        ),
        migrations.CreateModel(
            name='OutcomeIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('indicator_code', models.PositiveSmallIntegerField(help_text='User defined indicator code')),
                ('subindicator', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sub indicator')),
                ('definition', models.TextField(blank=True, null=True)),
                ('common_uom', models.CharField(blank=True, max_length=450, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.Indicator')),
                ('indicatortype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.IndicatorType', verbose_name='Indicator Type')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_outcomeindicator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Outcome Indicators',
            },
        ),
        migrations.CreateModel(
            name='ResearchOutcomeIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('experimentoutcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ExperimentOutcome', verbose_name='Experiment Outcome')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_researchoutcomeindicator', to=settings.AUTH_USER_MODEL)),
                ('outcomeindicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.OutcomeIndicator', verbose_name='Outcome indicator')),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Research Outcome Indicators',
            },
        ),
        migrations.CreateModel(
            name='SoilMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('upper_soil_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lower_soil_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depth_uom', models.CharField(blank=True, default='cm', max_length=8, null=True)),
                ('incubation_days', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_soilmeasurement', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Soil measurements',
            },
        ),
        migrations.CreateModel(
            name='Subpillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subpillar', models.CharField(max_length=50, unique=True)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_subpillar', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Subpillars',
            },
        ),
        migrations.AddField(
            model_name='researchoutcomeindicator',
            name='soilmeasurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.SoilMeasurement', verbose_name='Soil measurement'),
        ),
        migrations.AddField(
            model_name='researchoutcomeindicator',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicator',
            name='subpillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.Subpillar', verbose_name='Indicator subpillar'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='experimentoutcome',
            unique_together=set([('mean_outcome', 'outcome_uom')]),
        ),
    ]
