# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_researchoutcomeindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
