# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_auto_20170213_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomeindicator',
            name='subindicator',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sub indicator'),
        ),
        migrations.AlterField(
            model_name='researchoutcomeindicator',
            name='outcomeindicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.OutcomeIndicator', verbose_name='Outcome indicator'),
        ),
    ]
