# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_auto_20170419_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilmeasurement',
            name='depth_uom',
            field=models.CharField(default='cm', max_length=8),
        ),
    ]
