# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_soilmeasurement_depth_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchoutcomeindicator',
            name='soilmeasurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.SoilMeasurement', verbose_name='Soil measurement'),
        ),
    ]
