# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0007_auto_20170419_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('mean_outcome', models.DecimalField(decimal_places=2, max_digits=8)),
                ('std_outcome', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('outcome_uom', models.CharField(blank=True, default='kg/ha', max_length=100, null=True)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators_experimentoutcome', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Experiment Outcomes',
            },
        ),
        migrations.AlterField(
            model_name='soilmeasurement',
            name='depth_uom',
            field=models.CharField(blank=True, default='cm', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='researchoutcomeindicator',
            name='experimentoutcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ExperimentOutcome', verbose_name='Experiment Outcome'),
        ),
        migrations.AlterUniqueTogether(
            name='experimentoutcome',
            unique_together=set([('mean_outcome', 'std_outcome')]),
        ),
    ]
