# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_auto_20170419_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentoutcome',
            name='outcome_uom',
            field=models.CharField(default='kg/ha', max_length=100),
        ),
    ]
