# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_auto_20170419_1601'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experimentoutcome',
            unique_together=set([('mean_outcome', 'outcome_uom')]),
        ),
    ]
