from .csatheme.csathemeserializers import csa_theme_serializers
from .practicelevel.practicelevelserializers import practice_level_serializers
from .practicetype.practicetypeserializers import practice_type_serializers

csa_theme_serializers = csa_theme_serializers()
practice_level_serializers = practice_level_serializers()
practice_type_serializers = practice_type_serializers()
